# Use official Node.js image
FROM node:24-alpine3.21

# Set working directory
WORKDIR /app

# Copy and install dependencies
COPY package*.json .
RUN npm install

# Copy the rest of the backend source
COPY . .

# Expose backend port
EXPOSE 8000

# Start the backend server
CMD ["npm", "run", "dev"]
